### ISSUE TITLE
Sketch in same-named folder

### ISSUE THREAD

**Issue by jeremydouglass** [hamolicious/Processing-Terrain-Generation#1]
Thanks for sharing this sketch! 

Could you reorganize the repo so that the main .pde sketch matches the enclosing folder name? This way the sketch can be run when the repo is downloaded / cloned.

For example, rename sketch_191130a.pde to Processing-Terrain-Generation.pde

Or create a subfolder with any sketch name you want and put the sketch contents inside it.

Happy to submit a pull request if that would help....

**Comment by hamolicious** [comment]
Thank you for the suggestion, sorry it took so long
